### ISSUE TITLE
Not able to connect to the new UAVs after restarts

### ISSUE THREAD

**Issue by biabock** [A3Wasteland/ArmA3_Wasteland.Tanoa#1]
Hey,
As the new MQ-12 Falcon UAV is a blufor unit and the KH-3A Fenghuang UAV opfor, players from other factions are not able to connect to their drones after restart.
There is a way to add a "Force Connect" to these drones if the player in question is set as the owner?

**Comment by AgentRev** [comment]
I already fixed this like a week ago, are you running on properly-merged code?

**Comment by biabock** [comment]
I just have not updated the mission for today's Commits

**Comment by AgentRev** [comment]
The connect part is working fine on my end, although my UAV terminal disappears, which is a weird but separate issue.

**Comment by biabock** [comment]
I tested with vanila mission and has the same problem.
I did the following:
-Join as opfor and bought the MQ-12 Falcon (working well)
-The UAV showed the opfor icon
-Restart the server and join again as OPFOR
-The UAV spawn without the icon and it is impossible to connect
-so i change to blufor
-UAV with bluefor icon and now able to connect

**Comment by AgentRev** [comment]
I recorded the following with both Tanoa and Altis:
- Join as Blufor and bought the KH-3A (working well)
- The UAV showed the Blufor icon
- Restart the server and join again as Blufor
- The UAV has the Blufor icon and it is possible to connect

**Comment by biabock** [comment]
Thats what i mean, if you are from other faction you will not be able to connect after restart
MQ-12 Falcon UAV = bluefor only
KH-3A Fenghuang UAV = opfor only

**Comment by AgentRev** [comment]
Yes, the KH-3A is an **Op**for UAV, and **I** operate as **Blu**for, everything works fine after restart. I don't get what you mean.

**Comment by biabock** [comment]
When you buy, no matter your faction, the UAV will be assigned to you automatically.
But after the restart it can only be controlled by someone of default drone faction (Falcon=bluefor | Fenghuang=opfor)
I think a solution to this would be to add a "Force Connect" option to after the restart the person can connect to the drone in the same way that was assigned automatically when bought.

**Comment by AgentRev** [comment]
> But after the restart it can only be controlled by someone of your default drone faction

No, I cannot reproduce. The UAV is always assigned to the side of who bought it, regardless of the UAV's default side, and stays like so for multiple restarts.

> I think a solution to this would be to add a "Force Connect" option

No, this is a very bad idea that will cause bugs 100% certain.

**Comment by biabock** [comment]
> The UAV is always assigned to the side of who bought it, regardless of the UAV's default side, and stays like so for multiple restarts.

I did not know that
I think its not working 100% of the time, cuz the first time I tried to reproduce that it didnt work, but in the 2nd and 3rd works fine...
Thanks for the explanation, and sorry to waste your time
