### ISSUE TITLE
Another 2 bugs found after applying the mega update

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Tanoa#10]
1. No boat buttons in vehicle stores.
2. Thermal imaging is disabled in the laser disignator. I have A3W_disableBuiltInThermal set to 0.

**Comment by biabock** [comment]
Same here.
A3W_disableBuiltInThermal looks like not working right. Some times it block your thermal by nothing. But the laser not even have it :(

**Comment by biabock** [comment]
someone have an idea? I'm really trying to fix this before lauch the last days updates on my server xD

**Comment by nerdalertdk** [comment]
drawPlayerIcons.sqf line 189

`if (_noBuiltInThermal || (currentWeapon player) select [0,15] == "Laserdesignator") then`

try to remove this part ` || (currentWeapon player) select [0,15] == "Laserdesignator"`

**Comment by biabock** [comment]
already tried that
https://github.com/biabock/ArmA3_Wasteland.Tanoa/commit/c82ad86ba38cd0a1a220ff731267f069ee46750c

**Comment by nerdalertdk** [comment]
you still need `_noBuiltInThermal = ["A3W_disableBuiltInThermal"] call isConfigOn;`

else try comment out the entire code 

```
/*if (_noBuiltInThermal || (currentWeapon player) select [0,15] == "Laserdesignator") then
			{
				_thermalActive = currentVisionMode player isEqualTo 2;

				if (_thermalActive || !isNil "A3W_builtInThermalOffline") then
				{
					_weapon = currentWeapon player;
					_ownWeapon = true;

					{
						_x params ["_unit", "","","", "_ffv"];

						if (_unit == player) exitWith
						{
							_ownWeapon = _ffv;
						};
					} forEach fullCrew [objectParent player, "", false];

					if (_thermalActive && {cameraOn == vehicle player && _weapon in weapons player && _ownWeapon &&
						({_x == "TI"} count getArray (configFile >> "CfgWeapons" >> _weapon >> "visionMode") > 0 ||
						 {!("{_x == 'TI'} count getArray (_x >> 'visionMode') > 0" configClasses (configFile >> "CfgWeapons" >> _weapon >> "OpticsModes") isEqualTo [])})}) then
					{
						if (isNil "A3W_builtInThermalOffline") then
						{
							"A3W_thermalOffline" cutText ["THERMAL IMAGING OFFLINE", "BLACK", 0.001, false];
							A3W_builtInThermalOffline = true;
						};
					}
					else
					{
						if (!isNil "A3W_builtInThermalOffline") then
						{
							"A3W_thermalOffline" cutText ["", "PLAIN", 0.001, false];
							A3W_builtInThermalOffline = nil;
						};
					};
				};
			};*/
```

**Comment by biabock** [comment]
i actually did it...  look at my commit

**Comment by nerdalertdk** [comment]
Is IR working with the Viper Helmets or the new NVG with IR ?

**Comment by biabock** [comment]
yes, everything works fine, just the laser designator doesnt have thermal

**Comment by nerdalertdk** [comment]
I'm at work so can't test, but do they have thermal in the editor / Arsenal ?

**Comment by biabock** [comment]
yes, i still using the 'old' mission in my server and it is working

**Comment by biabock** [comment]
There is a reason to @AgentRev remove 'laser designator' here https://github.com/A3Wasteland/ArmA3_Wasteland.Tanoa/commit/f7171c03f1fb1416a22cc09b6a8f5ace0079b7e6#diff-11e90d95a389297f32428e7bc585fce4R15 ?

**Comment by Jermin** [comment]
Has this issue been fixed?

**Comment by biabock** [comment]
@Gigatek1 I realized you fixed laser designator... maybe you want to share what you did? xD

**Comment by Jermin** [comment]
The boat button reappears after disabling LouD's vehicle repainter.
