### ISSUE TITLE
Revive

### ISSUE THREAD

**Issue by Soloknight** [A3Wasteland/ArmA3_Wasteland.Tanoa#13]
I have looked in the logs and files and Revive isn't working any one else have this problem?

only thing I can find in the client logs
15:35:21 Class ReviveWoundedDefaultActions destroyed with lock count 1
15:35:21 Class ReviveMedicActions destroyed with lock count 1

**Comment by Soloknight** [comment]
Found the problem and Fixed, It's was human error lol

**Comment by Soloknight** [comment]
It's only on  the Tanoa server Stratis is working fine, Same files on both other then the custom map files

**Comment by Jermin** [comment]
It's working normally in my server.
