### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sp4wN7** [A3Wasteland/ArmA3_Wasteland.Tanoa#16]
Trying to start mission but get this:
"No entry 'bin\config.bin/CfgWorlds.tonoa'."

Makes the mission unplayable. Anything in the code perhaps?

**Comment by AgentRev** [comment]
# tonoa

I mean really...?

**Comment by Sp4wN7** [comment]
Lol, what noob mistake did I make? Ahhh Tanoa lol...

**Comment by AgentRev** [comment]
its TANOA not TONOA
