### ISSUE TITLE
No entry 'bin\config.bin/CfgWorlds.Tanoa-dev'.

### ISSUE THREAD

**Issue by Xav1erox** [A3Wasteland/ArmA3_Wasteland.Tanoa#19]
I use Tadst to run all of my private servers for friends. Altis and stratis work fine but when it comes to Tanoa i get this error No entry 'bin\config.bin/CfgWorlds.Tanoa-dev'. I correctly pack it into a pbo and updated A3Wasteland Settings and still get this error. Please help. Thanks

**Comment by biabock** [comment]
**Tanoa-dev**
rename your mision file to ArmA3_Wasteland.Tanoa.pbo
....

**Comment by Xav1erox** [comment]
Thanks
