### ISSUE TITLE
Vehicles wheels are stuck in the ground after 1.64 update

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Tanoa#25]
After the update, the wheels of all server-spawned and purchased vehicles are stuck in the ground, which makes it impossible to move them. Helos are not affected tho.

This happens on both Altis and Tanoa.

**Comment by codexGW** [comment]
That's what happens to vehicles when you set enableSimulation to false in
the editor. Haven't been able to update yet so it's a shot in the dark but
maybe that has something to do with it.

**Comment by Jermin** [comment]
Just tried it in the editor. With Enable Simulation off. The screen turns black as soon as I enter the vehicle. And the wheel models do not sink into the ground.

**Comment by AgentRev** [comment]
the black screen is not new, you can't use an unsimulated vehicle.

**Comment by codexGW** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/439. Use Altis for issues. It gets a lot more eyes on it. Unless its only map related.
