### ISSUE TITLE
Lower fps when joining server after 3 hours uptime than when being on server for 3 hours right after restart?

### ISSUE THREAD

**Issue by D4n2021** [A3Wasteland/ArmA3_Wasteland.Tanoa#26]
So is this ArmA 3 or wasteland issue? I mean it seems that in Tanoa wasteland when I stay on the server right after server restart for 3 hours I have MORE fps 3 hours into the game than when I join the server after 3 hours uptime (all with 60 players on server)... So sth. in the wasteland settings is handled differently when a client connects after 3 hours of server running time?

Or is this also happening with vanilla ArmA 3 servers? (In that case I can report that bug to BIA feedback bug tracker)

@AgentRev @nickludlam @JoSchaap

**Comment by nerdalertdk** [comment]
Wow why did you ping 3 people with this question? 

It's arma, it been like that since Arma 2
Google stuff before git post, also that's why almost every public arma server have an 3/4 restart cycle

**Comment by nerdalertdk** [comment]
Let me put it like this when in doubt it's always arma and it's broken game engine

**Comment by D4n2021** [comment]
sry pinged them cause srsly thought it's some wasteland issue/non-garbage-collection.

What and BIA DEVs don't even know what's causing this/have no performance analyze tool/garbage collection in ArmA 3 ???

**Comment by AgentRev** [comment]
![omg...](http://i.imgur.com/qX35BCV.jpg)

**Comment by D4n2021** [comment]
Lol I meant "thought" not "though" xD failll

**Comment by AgentRev** [comment]
Look, we've all been this naïve at some point; it's far more complex than just "omg BIS are incompetent??"

**Comment by codexGW** [comment]
I'll add this. When we switched to extdb from sock, we HAD to go from a 6 hour restart to 4 and 5 hours. Not sure why because there was a big Arma update in between. The only thing I can think of is the amount of saving or just engine related. With sock I just set it to save every hour (only bad if it crashes, but that doesn't happen much at all) because I could force a save right before a restart.

**Comment by D4n2021** [comment]
How do you know it's more complex? Do you know things about BIA developer tools that I don't? (I'd assume a company that big to have garbage collection and performance analyzing tools...)
