### ISSUE TITLE
Titan AT rocketlauncher zoom not working anymore since patch

### ISSUE THREAD

**Issue by D4n2021** [A3Wasteland/ArmA3_Wasteland.Tanoa#27]
What title says. Since today 10GB patch.

**Comment by AgentRev** [comment]
I don't think that would be a wasteland bug...

**Comment by D4n2021** [comment]
Oh no... -.- so another hotfix by BIA we have to wait for for days or even weeks... -.-

**Comment by D4n2021** [comment]
Ok reported it to BIA.
