### ISSUE TITLE
Vehicle Textures not saving 

### ISSUE THREAD

**Issue by eldrich71** [A3Wasteland/ArmA3_Wasteland.Tanoa#29]
I recently updated to 64bit/extDB3 A3 Tanoa everything seems to be working except vehicle texture saving I cant find anything in RPT to do with this, I started mod from vanilla and I'm up to date with that, also server was new rented from gaming deluxe (extDB2 worked fine on our old gaming deluxe server), I switched from my mod to vanilla and still get same issue any help would be appreciated as I have no idea :)

Cheers 
eld

**Comment by AgentRev** [comment]
Can you describe "not working" with more details?

**Comment by eldrich71** [comment]
sorry vehicle textures are not saving after server restart, yet when I test a couple of differant vehicles at the same time seems 1 does, forum post link http://forums.a3wasteland.com/index.php?topic=3414.0 I didn't want to write an essay on here :)

**Comment by eldrich71** [comment]
before and after restart 
![20170629175646_1](https://user-images.githubusercontent.com/11337139/27700258-f4003bb8-5cf4-11e7-93dc-c1e5e687619f.jpg)
![20170629180012_1](https://user-images.githubusercontent.com/11337139/27700261-fa1dfe86-5cf4-11e7-86b3-a1c5c1eae29b.jpg)


I still have no idea :(

**Comment by AgentRev** [comment]
Right so the plane worked but not the others... great

**Comment by eldrich71** [comment]
like I say ive no idea Ive seen saved helis around the map with textures so I'm thinking that works on occasion I will test just buying a heli tomorrow but land vehicles/boats ive tested loads and cant get to save the textures everything else seems ok

**Comment by AlexH0661** [comment]
Any progress on this?
I'm having a similar issue

**Comment by AgentRev** [comment]
I was never able to reproduce this bug at all.

**Comment by AlexH0661** [comment]
Is there anything we need to do with the "vehicleTextures_jpg_to_paa.sql" file? Or as long as it is present within the @extDB3 folder, it should all be good?

**Comment by AgentRev** [comment]
no that is very old, it was a one-time-use file between v1.1b and v1.2, in fact all SQL files are one-time-use.

**Comment by AlexH0661** [comment]
okay, I'll delete that one.
Going through the database, some of the player owned vehicals with textures have a texture listed, but others just have "[]". One of the players on my server noted that whenever the server is restarted, they lose the textures they had on the vehicles. Everything else saves perfectly though

**Comment by AgentRev** [comment]
[] is the default value.

**Comment by AlexH0661** [comment]
Thought so. I'll get in contact with the user to confirm that the vehicles they purchased with different textures, are definitely losing the textures between restarts.

**Comment by AlexH0661** [comment]
so, they purchased new vehicals with textures after the server restart which is why some had texture associated with them. They lost the textures on all their other vehicles

**Comment by eldrich71** [comment]
I'm still having this issue, I'm hoping when I update to V1.4 this week it will right itself

**Comment by ghost** [comment]
I'm on 1.4 and its not working either i'm afraid, 

purchased a hunter with the union jack camo http://puu.sh/xCVRd/e9db090701.jpg

The database saves the vehicle but not the texture http://puu.sh/xCVLr/2fb7172a5a.png

no errors in either rpt to report.

**Comment by AlexH0661** [comment]
I am on v1.4 as well. Receiving no errors in the rpt, or in the extDB3 log files

**Comment by AgentRev** [comment]
I finally managed to reproduce and fix the bug. https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/41d841111bfb5a653c6a54a5a4d797171866f1d6

**Comment by AlexH0661** [comment]
Awesome!!! :) Thanks for all your help!

**Comment by ghost** [comment]
Yes works great thanks
