### ISSUE TITLE
Mine direction after server reset & loss of cam nets after server reset

### ISSUE THREAD

**Issue by AlexH0661** [A3Wasteland/ArmA3_Wasteland.Tanoa#30]
After the server restarts, all mines reset to a default direction. Trip mines due West and SLAM mines due North.
Also, cam nets are lost between restarts

Apart from that, everything is running beautifully

**Comment by AgentRev** [comment]
Haven't tested, but this should fix mine direction: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/59f126115a25062d748a5aad7ae19c0a6192481f

I'll check later for camonets.

**Comment by AlexH0661** [comment]
Looks good! Thanks for fixing that :)

**Comment by AlexH0661** [comment]
Any updates regarding cam nets? :)

**Comment by AgentRev** [comment]
It's on the Altis repo, I haven't merged it yet: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/f96c7786e90aa8648f284476429510811f0bc1c0

**Comment by AlexH0661** [comment]
Awesome :) Thanks heaps!

**Comment by AlexH0661** [comment]
Implemented the changes, but the mines still don't seem to be saving. I'll try to look through the rtp and see if I can find anything

**Comment by AgentRev** [comment]
Wait, the mines don't save, like at all?

**Comment by AlexH0661** [comment]
Sorry, cam nets. The cam nets still aren't saving

**Comment by AgentRev** [comment]
Well it was working perfectly for me...

**Comment by AlexH0661** [comment]
I'll try again :)

**Comment by AlexH0661** [comment]
Got it working, I think I must have missed a file the first time. Looks all good now 👍

**Comment by AlexH0661** [comment]
This can be marked as resolved :)
