### ISSUE TITLE
FIA Camonet Cache - Weapons lose attachments

### ISSUE THREAD

**Issue by AlexH0661** [A3Wasteland/ArmA3_Wasteland.Tanoa#32]
Weapons stored in FIA camonet cache loose their attachments after server restart

**Comment by AgentRev** [comment]
Yup, you can thank Bohemia for not giving me a way to attach stuff to inventory weapons. ¯\\\_(ツ)_/¯

**Comment by AlexH0661** [comment]
This was tested with the MX3GL 6.5 rifle.
No problems, at least it is a known issue :)
