### ISSUE TITLE
More clarification than an issue - Terratory Payments

### ISSUE THREAD

**Issue by AlexH0661** [A3Wasteland/ArmA3_Wasteland.Tanoa#33]
When does the 60 mins (or x minutes) for the payment start? Is it from the time of the last captured territory? Users are saying the payment times are inconsistent, but I believe this might be due to how they portray the payment time to work.

**Comment by AgentRev** [comment]
By default it's 30 minutes, however it's an old script and it wasn't written to compensate for lag-induced time dilation, so under heavy server load it can take an hour or more.

**Comment by AlexH0661** [comment]
no problems. I have it set for 60 mins, but sometimes it'll take 70 mins, etc, etc. Not a huge deal just wanted to clarify how it worked :)

**Comment by AgentRev** [comment]
Also the payroll timer only starts when the very first territory is captured.

**Comment by AlexH0661** [comment]
and then from there on the payment is based on the first territory capture?

**Comment by AgentRev** [comment]
No, the payment is recalculated from all territories at the moment it's executed. The payroll script simply stays idle at server start while all territories are neutral, and the timer starts on the first capture.
