### ISSUE TITLE
1. Group Management  2. Game title/web address now on hud (how to remove)

### ISSUE THREAD

**Issue by BeardedBushman** [A3Wasteland/ArmA3_Wasteland.Tanoa#37]
1. Since the admin @AlexH0661 changed a few settings on the server the other day I have no names in the group management now to invite players, also no names for players who have sent the invite.

2. I don't know if it's related to the above but during the same settings changes I experienced something strange which no one else I play with has on their screen, when the admin changed something I now have "A3wasteland Tanoa A3wastealnd.com" above my hud on the bottom right of the screen, right where I usually have my right panel for gps, how do I remove this ? Screenshot of what I now see for both issues, any help appreciated as I like to have a clear hud to make art from my screenshots.
Thankx.
https://steamcommunity.com/sharedfiles/filedetails/?id=1379198401

**Comment by BeardedBushman** [comment]
I fixed it, what ever changes we made it had a corrupted my player profile file, lucky I do a backup every month, I loaded up april file and no more on screeen text and group management works again.

**Comment by AgentRev** [comment]
If the problem happens again:

![upci7eh](https://user-images.githubusercontent.com/1380241/39835208-749c889a-539d-11e8-8c9d-9b671ace0353.png)
