### ISSUE TITLE
Bug in storeOwners.sqf

### ISSUE THREAD

**Issue by TheGhostDog** [A3Wasteland/ArmA3_Wasteland.Tanoa#39]
Hello AgentRev,

I noticed a little bug in storeOwners.sqf.
Exlusion Boats does not work with VehStore (it's the only one, I tested the others)

Hoping this can help you.

Sincerely,

PS: Thank you for your Efforts and your Work ! ;)

**Comment by AgentRev** [comment]
Yes, the purpose of the boat exclusion was to prevent boats from being purchased if there is no water, however in v1.4c I made it possible to purchase boats on land so they can be towed to water to increase gameplay versatility. I didn't want to touch storeOwners to prevent unnecessary conflicts downstream and to prevent server owners from having to alter it manually to take effect, so I disabled the exclusion directly in loadVehicleStore: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/ad01ff131e8bb4685e18e34fe66b712bb3b74432/client/systems/vehicleStore/loadVehicleStore.sqf#L66-L69

You can manually uncomment `case "boats"` if you wish to use the exclusion.

**Comment by TheGhostDog** [comment]
Thank you for your answer as fast as clear.

I fully understand your choice.

I found a little further the part you told me about:

_marker = _marker + (["_seaSpawn", "_ landSpawn"] select (markerType (_marker + "_seaSpawn") isEqualTo ""));

Thank you for your advice, but do not worry, my report was just for the purpose of helping you.

Personally I am doing a global modification of your beautiful mod, in order to make it RP (totally suggestive and personal choice).

Besides, if you're interested, can I tell you about it on your forum ?

Thanks again.

Sincerely,

PS: Sorry my bad english: P
