### ISSUE TITLE
Store markers disappear after the mega update

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Tanoa#7]
After merging the mega update, vehicle store and general store makers are no longer shown on the map.

I can't find any errors in the rpt log. How should I debug this issue?

**Comment by AgentRev** [comment]
make sure your client init.sqf matches the vanilla one, what are your settings for parking and storage?

**Comment by Jermin** [comment]
I didn't touch the settings for parking and storage. Will check client/init.sqf.

**Comment by AgentRev** [comment]
what is your saving method

**Comment by Jermin** [comment]
I've been testing in my local server. Both Altis and Tanoa have this issue. Will test again in my production servers.

**Comment by AgentRev** [comment]
what is your saving method.

**Comment by Jermin** [comment]
It is extDB (in default_config.sqf). But the mission will fall back to profile locally?

**Comment by AgentRev** [comment]
is that a question or a observed fact

**Comment by dustinslane** [comment]
Having this too on a fresh pull off of dev. Using profile saving, testing extDB now

**Comment by AgentRev** [comment]
yeah it's broken for profile and iniDB if that's what you want to know

**Comment by dustinslane** [comment]
can confirm: works on extDB. Thanks!

**Comment by Jermin** [comment]
Thank goodness! It was a false alarm.

**Comment by nerdalertdk** [comment]
Fixes it, my merged had fucked up, init.sqf, and had not added  [] execVM "addons\parking\functions.sqf";

**Comment by nerdalertdk** [comment]
PS. the mine options is missing from the default|main_config

A3W_mineSaving				= 0;
A3W_mineLifetime		 		= 1*60;

**Comment by nerdalertdk** [comment]
I can see gunstore and private storage, rest is gone

**Comment by hobart666** [comment]
I'm noticing that VehStore6's map marker isn't showing up in Tanoa for some reason.

**Comment by AgentRev** [comment]
> I'm noticing that VehStore6's map marker isn't showing up in Tanoa for some reason.

I never had this problem... it's the bottom-left one

**Comment by hobart666** [comment]
Yes its the bottom left one and I see this in createVehicleStoreMarkers.sqf  `if (!isPlayer _x && {["VehStore6", name _x] call fn_startsWith}) then
    {
        _npcPos = getPos _x;
        _markerName = format["marker_shop_title_%1",_x];
        deleteMarkerLocal _markerName;
    };
} forEach entities "CAManBase";` would that be making it not show?

**Comment by AgentRev** [comment]
I have no idea what the heck is that.

**Comment by hobart666** [comment]
erm nevermind I see the issue, its old from my dirty merge, I'm going to hide. From a private store. in an older mission.
