### ISSUE TITLE
SetVariable Restriction #3 kick after selecting class.

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Tanoa#9]
`- #3 "bounty" = 0 2:1545 O_medic_F`

**Comment by AgentRev** [comment]
yeah I updated the filter but I forgot to push the related commits to the actual mission...

**Comment by nerdalertdk** [comment]
Please share fix

**Comment by AgentRev** [comment]
remove the filter until fixed...
